import React, { useState, useEffect } from 'react';
import {
  User,
  Building,
  CreditCard,
  Shield,
  Bell,
  Palette,
  Save,
  Upload,
  Eye,
  EyeOff,
  Loader,
  CheckCircle,
  AlertCircle,
  Wand2
} from 'lucide-react';
import type { Organizer } from '../../lib/supabase';
import { SettingsService, SUPPORTED_CURRENCIES } from '../../services/settingsService';
import { CurrencyService } from '../../services/currencyService';
import { useTheme } from '../../contexts/ThemeContext';

interface SettingsProps {
  organizer: Organizer | null;
}

const COLOR_PRESETS = [
  { name: 'Ocean Blue', primary: '#001B79', secondary: '#0066CC' },
  { name: 'Forest Green', primary: '#065F46', secondary: '#10B981' },
  { name: 'Sunset Orange', primary: '#C2410C', secondary: '#F97316' },
  { name: 'Royal Purple', primary: '#6B21A8', secondary: '#A855F7' },
  { name: 'Cherry Red', primary: '#991B1B', secondary: '#EF4444' },
  { name: 'Teal', primary: '#0F766E', secondary: '#14B8A6' },
  { name: 'Amber', primary: '#B45309', secondary: '#F59E0B' },
  { name: 'Pink', primary: '#BE185D', secondary: '#EC4899' },
];

const Settings: React.FC<SettingsProps> = ({ organizer }) => {
  const theme = useTheme();
  const [activeTab, setActiveTab] = useState('branding');
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [exchangeRates, setExchangeRates] = useState<{ [key: string]: number }>({});
  const [isLoadingRates, setIsLoadingRates] = useState(false);

  const [profileData, setProfileData] = useState({
    firstName: organizer?.first_name || '',
    lastName: organizer?.last_name || '',
    email: organizer?.email || '',
    phone: organizer?.phone || '',
    location: organizer?.location || '',
    organizationName: organizer?.organization_name || '',
    eventTypes: organizer?.event_types || []
  });

  const [brandingData, setBrandingData] = useState({
    logo: null as File | null,
    logoUrl: '',
    primaryColor: '#001B79',
    secondaryColor: '#0066CC',
    themeAutoGenerated: false,
    eventPageTemplate: 'modern'
  });

  const [currencySettings, setCurrencySettings] = useState({
    defaultCurrency: 'USD',
    currencySymbol: '$'
  });

  const [notificationSettings, setNotificationSettings] = useState({
    emailNotifications: true,
    smsNotifications: false,
    newRegistrations: true,
    paymentUpdates: true,
    eventReminders: true,
    marketingEmails: false
  });

  const [passwordData, setPasswordData] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: ''
  });

  useEffect(() => {
    if (organizer) {
      loadPreferences();
      loadExchangeRates();
    }
  }, [organizer]);

  const loadPreferences = async () => {
    if (!organizer) return;

    setIsLoading(true);
    const result = await SettingsService.getOrganizerPreferences(organizer.id);

    if (result.success && result.preferences) {
      const prefs = result.preferences;
      setBrandingData({
        logo: null,
        logoUrl: prefs.logoUrl || '',
        primaryColor: prefs.primaryColor,
        secondaryColor: prefs.secondaryColor,
        themeAutoGenerated: prefs.themeAutoGenerated,
        eventPageTemplate: prefs.eventPageTemplate
      });

      setCurrencySettings({
        defaultCurrency: prefs.defaultCurrency,
        currencySymbol: prefs.currencySymbol
      });

      setNotificationSettings({
        emailNotifications: prefs.notificationEmail,
        smsNotifications: prefs.notificationSms,
        newRegistrations: prefs.notificationNewRegistrations,
        paymentUpdates: prefs.notificationPaymentUpdates,
        eventReminders: prefs.notificationEventReminders,
        marketingEmails: prefs.notificationMarketing
      });
    }

    setIsLoading(false);
  };

  const loadExchangeRates = async () => {
    setIsLoadingRates(true);
    const baseCurrency = currencySettings.defaultCurrency || 'USD';
    const result = await CurrencyService.getLiveExchangeRates(baseCurrency);
    if (result.success && result.rates) {
      setExchangeRates(result.rates);
    }
    setIsLoadingRates(false);
  };

  const showMessage = (type: 'success' | 'error', text: string) => {
    setMessage({ type, text });
    setTimeout(() => setMessage(null), 5000);
  };

  const eventTypeOptions = [
    'Corporate Events',
    'Conferences & Seminars',
    'Workshops & Training',
    'Networking Events',
    'Product Launches',
    'Trade Shows',
    'Social Events',
    'Fundraising Events'
  ];

  const handleProfileChange = (field: string, value: any) => {
    setProfileData(prev => ({ ...prev, [field]: value }));
  };

  const handleEventTypeToggle = (eventType: string) => {
    setProfileData(prev => ({
      ...prev,
      eventTypes: prev.eventTypes.includes(eventType)
        ? prev.eventTypes.filter(type => type !== eventType)
        : [...prev.eventTypes, eventType]
    }));
  };

  const handleSaveProfile = async () => {
    if (!organizer) return;

    setIsSaving(true);
    const result = await SettingsService.updateProfile(organizer.id, profileData);

    if (result.success) {
      showMessage('success', 'Profile updated successfully');
    } else {
      showMessage('error', result.error || 'Failed to update profile');
    }

    setIsSaving(false);
  };

  const handleLogoUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file || !organizer) return;

    // Validate file size (max 5MB)
    if (file.size > 5 * 1024 * 1024) {
      showMessage('error', 'Logo file size must be less than 5MB');
      return;
    }

    // Validate file type
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    if (!allowedTypes.includes(file.type)) {
      showMessage('error', 'Only JPG, PNG, and WebP images are allowed');
      return;
    }

    setBrandingData(prev => ({ ...prev, logo: file }));

    const colors = await SettingsService.extractColorsFromImage(file);
    setBrandingData(prev => ({
      ...prev,
      primaryColor: colors.primaryColor,
      secondaryColor: colors.secondaryColor,
      themeAutoGenerated: true
    }));

    showMessage('success', 'Logo selected! Theme colors extracted. Click "Save Branding" to upload.');
  };

  const applyColorPreset = (preset: { primary: string; secondary: string }) => {
    setBrandingData(prev => ({
      ...prev,
      primaryColor: preset.primary,
      secondaryColor: preset.secondary,
      themeAutoGenerated: false
    }));
  };

  const handleSaveBranding = async () => {
    if (!organizer) return;

    setIsSaving(true);

    let logoUrl = brandingData.logoUrl;

    if (brandingData.logo) {
      const uploadResult = await SettingsService.uploadLogo(organizer.id, brandingData.logo);
      if (!uploadResult.success) {
        showMessage('error', uploadResult.error || 'Failed to upload logo');
        setIsSaving(false);
        return;
      }
      logoUrl = uploadResult.url || logoUrl;
    }

    const result = await SettingsService.updateOrganizerPreferences(organizer.id, {
      primaryColor: brandingData.primaryColor,
      secondaryColor: brandingData.secondaryColor,
      themeAutoGenerated: brandingData.themeAutoGenerated,
      eventPageTemplate: brandingData.eventPageTemplate,
      logoUrl
    });

    if (result.success) {
      // Update theme context
      theme.updateTheme({
        primary: brandingData.primaryColor,
        secondary: brandingData.secondaryColor
      });
      if (logoUrl) {
        theme.updateLogo(logoUrl);
      }
      showMessage('success', 'Branding settings saved successfully');
    } else {
      showMessage('error', result.error || 'Failed to save branding');
    }

    setIsSaving(false);
  };

  const handleCurrencyChange = async (currencyCode: string) => {
    const currency = SUPPORTED_CURRENCIES.find(c => c.code === currencyCode);
    if (!currency || !organizer) return;

    setIsLoadingRates(true);

    setCurrencySettings({
      defaultCurrency: currency.code,
      currencySymbol: currency.symbol
    });

    const result = await SettingsService.updateOrganizerPreferences(organizer.id, {
      defaultCurrency: currency.code,
      currencySymbol: currency.symbol
    });

    if (result.success) {
      // Update theme context
      theme.updateCurrency(currency.code, currency.symbol);
      showMessage('success', `Currency changed to ${currency.name}. Loading exchange rates...`);

      // Reload exchange rates for new currency
      const ratesResult = await CurrencyService.getLiveExchangeRates(currency.code);
      if (ratesResult.success && ratesResult.rates) {
        setExchangeRates(ratesResult.rates);
      }
    } else {
      showMessage('error', result.error || 'Failed to update currency');
    }

    setIsLoadingRates(false);
  };

  const handleSaveNotifications = async () => {
    if (!organizer) return;

    setIsSaving(true);
    const result = await SettingsService.updateOrganizerPreferences(organizer.id, {
      notificationEmail: notificationSettings.emailNotifications,
      notificationSms: notificationSettings.smsNotifications,
      notificationNewRegistrations: notificationSettings.newRegistrations,
      notificationPaymentUpdates: notificationSettings.paymentUpdates,
      notificationEventReminders: notificationSettings.eventReminders,
      notificationMarketing: notificationSettings.marketingEmails
    });

    if (result.success) {
      showMessage('success', 'Notification preferences saved');
    } else {
      showMessage('error', result.error || 'Failed to save notifications');
    }

    setIsSaving(false);
  };

  const handleChangePassword = async () => {
    if (passwordData.newPassword !== passwordData.confirmPassword) {
      showMessage('error', 'New passwords do not match');
      return;
    }

    if (passwordData.newPassword.length < 6) {
      showMessage('error', 'Password must be at least 6 characters');
      return;
    }

    setIsSaving(true);
    const result = await SettingsService.changePassword(
      passwordData.currentPassword,
      passwordData.newPassword
    );

    if (result.success) {
      showMessage('success', 'Password changed successfully');
      setPasswordData({ currentPassword: '', newPassword: '', confirmPassword: '' });
    } else {
      showMessage('error', result.error || 'Failed to change password');
    }

    setIsSaving(false);
  };

  const handleDeleteAccount = async () => {
    if (!organizer) return;

    const confirmed = window.confirm(
      'Are you sure you want to delete your account? This action cannot be undone and will delete all your events and data.'
    );

    if (!confirmed) return;

    setIsSaving(true);
    const result = await SettingsService.deleteAccount(organizer.id);

    if (result.success) {
      window.location.href = '/';
    } else {
      showMessage('error', result.error || 'Failed to delete account');
      setIsSaving(false);
    }
  };

  const tabs = [
    { id: 'profile', name: 'Profile', icon: User },
    { id: 'branding', name: 'Branding', icon: Palette },
    { id: 'payments', name: 'Payments', icon: CreditCard },
    { id: 'notifications', name: 'Notifications', icon: Bell },
    { id: 'security', name: 'Security', icon: Shield }
  ];

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader className="w-8 h-8 animate-spin text-primary-500" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Settings</h1>
        <p className="text-gray-600 mt-1">Manage your account and preferences</p>
      </div>

      {message && (
        <div
          className={`rounded-lg p-4 flex items-center space-x-3 ${
            message.type === 'success'
              ? 'bg-green-50 border border-green-200'
              : 'bg-red-50 border border-red-200'
          }`}
        >
          {message.type === 'success' ? (
            <CheckCircle className="h-5 w-5 text-green-500" />
          ) : (
            <AlertCircle className="h-5 w-5 text-red-500" />
          )}
          <span
            className={
              message.type === 'success' ? 'text-green-800' : 'text-red-800'
            }
          >
            {message.text}
          </span>
        </div>
      )}

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100">
        <div className="border-b border-gray-200">
          <nav className="flex space-x-8 px-6">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`py-4 px-1 border-b-2 font-medium text-sm flex items-center space-x-2 transition-colors ${
                    activeTab === tab.id
                      ? 'border-primary-500 text-primary-600'
                      : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                  }`}
                >
                  <Icon className="h-4 w-4" />
                  <span>{tab.name}</span>
                </button>
              );
            })}
          </nav>
        </div>

        <div className="p-6">
          {activeTab === 'profile' && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">Profile Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">First Name</label>
                    <input
                      type="text"
                      value={profileData.firstName}
                      onChange={(e) => handleProfileChange('firstName', e.target.value)}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Last Name</label>
                    <input
                      type="text"
                      value={profileData.lastName}
                      onChange={(e) => handleProfileChange('lastName', e.target.value)}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Email</label>
                    <input
                      type="email"
                      value={profileData.email}
                      disabled
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 bg-gray-50 text-gray-500 cursor-not-allowed"
                    />
                    <p className="text-xs text-gray-500 mt-1">Email cannot be changed</p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Phone</label>
                    <input
                      type="tel"
                      value={profileData.phone}
                      onChange={(e) => handleProfileChange('phone', e.target.value)}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                    />
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-2">Organization Name</label>
                    <input
                      type="text"
                      value={profileData.organizationName}
                      onChange={(e) => handleProfileChange('organizationName', e.target.value)}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                    />
                  </div>
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-2">Location</label>
                    <input
                      type="text"
                      value={profileData.location}
                      onChange={(e) => handleProfileChange('location', e.target.value)}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                      placeholder="City, State/Country"
                    />
                  </div>
                </div>
              </div>

              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">Event Types</h3>
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                  {eventTypeOptions.map((eventType) => (
                    <label
                      key={eventType}
                      className={`relative flex items-center p-3 rounded-lg border cursor-pointer transition-colors ${
                        profileData.eventTypes.includes(eventType)
                          ? 'border-primary-500 bg-primary-50'
                          : 'border-gray-300 hover:border-primary-300'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={profileData.eventTypes.includes(eventType)}
                        onChange={() => handleEventTypeToggle(eventType)}
                        className="sr-only"
                      />
                      <span className="text-sm font-medium text-gray-700">{eventType}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="flex justify-end">
                <button
                  onClick={handleSaveProfile}
                  disabled={isSaving}
                  className="flex items-center space-x-2 bg-primary-500 text-white px-6 py-2 rounded-lg font-medium hover:bg-primary-600 transition-colors disabled:opacity-50"
                >
                  {isSaving ? <Loader className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>{isSaving ? 'Saving...' : 'Save Changes'}</span>
                </button>
              </div>
            </div>
          )}

          {activeTab === 'branding' && (
            <div className="space-y-8">
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">Brand Customization</h3>
                <p className="text-gray-600 mb-6">Customize your organization's branding and appearance across all event pages.</p>

                <div className="space-y-8">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-3">Organization Logo</label>
                    <div className="flex items-center space-x-6">
                      <div className="w-24 h-24 bg-gray-100 rounded-xl flex items-center justify-center border-2 border-dashed border-gray-300">
                        {brandingData.logo ? (
                          <img
                            src={URL.createObjectURL(brandingData.logo)}
                            alt="Logo preview"
                            className="w-full h-full object-cover rounded-xl"
                          />
                        ) : brandingData.logoUrl ? (
                          <img
                            src={brandingData.logoUrl}
                            alt="Current logo"
                            className="w-full h-full object-cover rounded-xl"
                          />
                        ) : (
                          <Building className="h-8 w-8 text-gray-400" />
                        )}
                      </div>
                      <div className="flex-1">
                        <input
                          type="file"
                          accept="image/*"
                          onChange={handleLogoUpload}
                          className="hidden"
                          id="logo-upload"
                        />
                        <label
                          htmlFor="logo-upload"
                          className="inline-flex items-center space-x-2 bg-white border border-gray-300 text-gray-700 px-4 py-2 rounded-lg font-medium hover:bg-gray-50 cursor-pointer transition-colors"
                        >
                          <Upload className="h-4 w-4" />
                          <span>Upload Logo</span>
                        </label>
                        <p className="text-xs text-gray-500 mt-2">PNG, JPG, WebP up to 5MB. Theme colors will be auto-extracted from your logo.</p>
                      </div>
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <h4 className="text-md font-medium text-gray-900">Brand Colors</h4>
                      {brandingData.themeAutoGenerated && (
                        <div className="flex items-center space-x-2 text-sm text-green-600">
                          <Wand2 className="h-4 w-4" />
                          <span>Auto-generated from logo</span>
                        </div>
                      )}
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-3">Primary Color</label>
                        <div className="flex items-center space-x-3">
                          <input
                            type="color"
                            value={brandingData.primaryColor}
                            onChange={(e) => setBrandingData(prev => ({ ...prev, primaryColor: e.target.value, themeAutoGenerated: false }))}
                            className="w-12 h-12 rounded-lg border border-gray-300 cursor-pointer"
                          />
                          <input
                            type="text"
                            value={brandingData.primaryColor}
                            onChange={(e) => setBrandingData(prev => ({ ...prev, primaryColor: e.target.value, themeAutoGenerated: false }))}
                            className="flex-1 rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 font-mono text-sm"
                            placeholder="#001B79"
                          />
                        </div>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-3">Secondary Color</label>
                        <div className="flex items-center space-x-3">
                          <input
                            type="color"
                            value={brandingData.secondaryColor}
                            onChange={(e) => setBrandingData(prev => ({ ...prev, secondaryColor: e.target.value, themeAutoGenerated: false }))}
                            className="w-12 h-12 rounded-lg border border-gray-300 cursor-pointer"
                          />
                          <input
                            type="text"
                            value={brandingData.secondaryColor}
                            onChange={(e) => setBrandingData(prev => ({ ...prev, secondaryColor: e.target.value, themeAutoGenerated: false }))}
                            className="flex-1 rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 font-mono text-sm"
                            placeholder="#0066CC"
                          />
                        </div>
                      </div>
                    </div>

                    <div className="mt-6">
                      <h4 className="text-sm font-medium text-gray-700 mb-3">Color Presets</h4>
                      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-3">
                        {COLOR_PRESETS.map((preset) => (
                          <button
                            key={preset.name}
                            onClick={() => applyColorPreset({ primary: preset.primary, secondary: preset.secondary })}
                            className="group relative"
                            title={preset.name}
                          >
                            <div className="flex space-x-1 p-2 rounded-lg border-2 border-gray-200 hover:border-gray-400 transition-all hover:scale-105">
                              <div
                                className="w-6 h-6 rounded"
                                style={{ backgroundColor: preset.primary }}
                              ></div>
                              <div
                                className="w-6 h-6 rounded"
                                style={{ backgroundColor: preset.secondary }}
                              ></div>
                            </div>
                            <span className="absolute -bottom-6 left-1/2 transform -translate-x-1/2 text-xs text-gray-600 opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
                              {preset.name}
                            </span>
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="bg-gray-50 rounded-xl p-6">
                    <h4 className="text-md font-medium text-gray-900 mb-4">Color Preview</h4>
                    <div className="flex space-x-4">
                      <div
                        className="w-20 h-20 rounded-lg shadow-sm border border-gray-200"
                        style={{ backgroundColor: brandingData.primaryColor }}
                      ></div>
                      <div
                        className="w-20 h-20 rounded-lg shadow-sm border border-gray-200"
                        style={{ backgroundColor: brandingData.secondaryColor }}
                      ></div>
                      <div
                        className="w-20 h-20 rounded-lg shadow-sm border border-gray-200"
                        style={{
                          background: `linear-gradient(135deg, ${brandingData.primaryColor} 0%, ${brandingData.secondaryColor} 100%)`
                        }}
                      ></div>
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-3">Event Page Template</label>
                    <select
                      value={brandingData.eventPageTemplate}
                      onChange={(e) => setBrandingData(prev => ({ ...prev, eventPageTemplate: e.target.value }))}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                    >
                      <option value="modern">Modern</option>
                      <option value="classic">Classic</option>
                      <option value="minimal">Minimal</option>
                      <option value="corporate">Corporate</option>
                    </select>
                    <p className="text-sm text-gray-500 mt-2">Choose the layout style for your event pages</p>
                  </div>
                </div>
              </div>

              <div className="flex justify-end pt-6 border-t border-gray-200">
                <button
                  onClick={handleSaveBranding}
                  disabled={isSaving}
                  className="flex items-center space-x-2 bg-primary-500 text-white px-6 py-2 rounded-lg font-medium hover:bg-primary-600 transition-colors disabled:opacity-50"
                >
                  {isSaving ? <Loader className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>{isSaving ? 'Saving...' : 'Save Branding'}</span>
                </button>
              </div>
            </div>
          )}

          {activeTab === 'payments' && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">Payment Settings</h3>

                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-3">Default Currency</label>
                    <select
                      value={currencySettings.defaultCurrency}
                      onChange={(e) => handleCurrencyChange(e.target.value)}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                    >
                      {SUPPORTED_CURRENCIES.map((currency) => (
                        <option key={currency.code} value={currency.code}>
                          {currency.symbol} {currency.code} - {currency.name}
                        </option>
                      ))}
                    </select>
                    <p className="text-sm text-gray-500 mt-2">
                      This currency will be used for all event pricing. Exchange rates are updated in real-time.
                    </p>
                  </div>

                  {isLoadingRates ? (
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                      <div className="flex items-center justify-center space-x-3">
                        <Loader className="w-5 h-5 animate-spin text-gray-400" />
                        <span className="text-gray-600">Loading exchange rates...</span>
                      </div>
                    </div>
                  ) : Object.keys(exchangeRates).length > 0 && (
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                      <div className="flex items-center justify-between mb-4">
                        <h4 className="text-md font-medium text-gray-900">Live Exchange Rates</h4>
                        <button
                          onClick={loadExchangeRates}
                          className="text-xs text-primary-600 hover:text-primary-700 font-medium"
                        >
                          Refresh Rates
                        </button>
                      </div>
                      <p className="text-sm text-gray-600 mb-4">
                        Current rates for 1 {currencySettings.defaultCurrency}:
                      </p>
                      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                        {SUPPORTED_CURRENCIES.filter(c => c.code !== currencySettings.defaultCurrency).slice(0, 8).map((currency) => {
                          const rate = exchangeRates[currency.code];
                          return rate ? (
                            <div
                              key={currency.code}
                              className="bg-white rounded-lg p-3 border border-gray-200"
                            >
                              <div className="flex items-center justify-between">
                                <span className="text-sm font-medium text-gray-900">{currency.code}</span>
                                <span className="text-xs text-gray-500">{currency.symbol}</span>
                              </div>
                              <div className="text-lg font-semibold text-primary-600 mt-1">
                                {rate.toFixed(2)}
                              </div>
                            </div>
                          ) : null;
                        })}
                      </div>
                      <p className="text-xs text-gray-500 mt-4">
                        Exchange rates are updated every hour and cached locally for performance.
                      </p>
                    </div>
                  )}

                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                    <div className="flex items-center space-x-3">
                      <CreditCard className="h-5 w-5 text-blue-500" />
                      <div>
                        <h4 className="font-medium text-blue-900">Payment Processing</h4>
                        <p className="text-sm text-blue-700">Connect Paystack to accept payments for your events</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'notifications' && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">Notification Preferences</h3>

                <div className="space-y-4">
                  <div className="flex items-center justify-between py-3 border-b border-gray-200">
                    <div>
                      <h4 className="font-medium text-gray-900">Email Notifications</h4>
                      <p className="text-sm text-gray-500">Receive notifications via email</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={notificationSettings.emailNotifications}
                        onChange={(e) => setNotificationSettings(prev => ({ ...prev, emailNotifications: e.target.checked }))}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-500"></div>
                    </label>
                  </div>

                  <div className="flex items-center justify-between py-3 border-b border-gray-200">
                    <div>
                      <h4 className="font-medium text-gray-900">SMS Notifications</h4>
                      <p className="text-sm text-gray-500">Receive notifications via SMS</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={notificationSettings.smsNotifications}
                        onChange={(e) => setNotificationSettings(prev => ({ ...prev, smsNotifications: e.target.checked }))}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-500"></div>
                    </label>
                  </div>

                  <div className="flex items-center justify-between py-3 border-b border-gray-200">
                    <div>
                      <h4 className="font-medium text-gray-900">New Registrations</h4>
                      <p className="text-sm text-gray-500">Get notified when someone registers for your events</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={notificationSettings.newRegistrations}
                        onChange={(e) => setNotificationSettings(prev => ({ ...prev, newRegistrations: e.target.checked }))}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-500"></div>
                    </label>
                  </div>

                  <div className="flex items-center justify-between py-3 border-b border-gray-200">
                    <div>
                      <h4 className="font-medium text-gray-900">Payment Updates</h4>
                      <p className="text-sm text-gray-500">Receive updates about payments and refunds</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={notificationSettings.paymentUpdates}
                        onChange={(e) => setNotificationSettings(prev => ({ ...prev, paymentUpdates: e.target.checked }))}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-500"></div>
                    </label>
                  </div>

                  <div className="flex items-center justify-between py-3 border-b border-gray-200">
                    <div>
                      <h4 className="font-medium text-gray-900">Event Reminders</h4>
                      <p className="text-sm text-gray-500">Get reminders about upcoming events</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={notificationSettings.eventReminders}
                        onChange={(e) => setNotificationSettings(prev => ({ ...prev, eventReminders: e.target.checked }))}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-500"></div>
                    </label>
                  </div>

                  <div className="flex items-center justify-between py-3">
                    <div>
                      <h4 className="font-medium text-gray-900">Marketing Emails</h4>
                      <p className="text-sm text-gray-500">Receive marketing emails and product updates</p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        checked={notificationSettings.marketingEmails}
                        onChange={(e) => setNotificationSettings(prev => ({ ...prev, marketingEmails: e.target.checked }))}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-primary-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary-500"></div>
                    </label>
                  </div>
                </div>

                <div className="flex justify-end pt-6 border-t border-gray-200 mt-6">
                  <button
                    onClick={handleSaveNotifications}
                    disabled={isSaving}
                    className="flex items-center space-x-2 bg-primary-500 text-white px-6 py-2 rounded-lg font-medium hover:bg-primary-600 transition-colors disabled:opacity-50"
                  >
                    {isSaving ? <Loader className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                    <span>{isSaving ? 'Saving...' : 'Save Preferences'}</span>
                  </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'security' && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-medium text-gray-900 mb-4">Security Settings</h3>

                <div className="space-y-6">
                  <div>
                    <h4 className="font-medium text-gray-900 mb-3">Change Password</h4>
                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Current Password</label>
                        <div className="relative">
                          <input
                            type={showPassword ? "text" : "password"}
                            value={passwordData.currentPassword}
                            onChange={(e) => setPasswordData(prev => ({ ...prev, currentPassword: e.target.value }))}
                            className="w-full rounded-lg border border-gray-300 px-3 py-2 pr-10 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                          />
                          <button
                            type="button"
                            onClick={() => setShowPassword(!showPassword)}
                            className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                          >
                            {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                          </button>
                        </div>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">New Password</label>
                        <input
                          type="password"
                          value={passwordData.newPassword}
                          onChange={(e) => setPasswordData(prev => ({ ...prev, newPassword: e.target.value }))}
                          className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Confirm New Password</label>
                        <input
                          type="password"
                          value={passwordData.confirmPassword}
                          onChange={(e) => setPasswordData(prev => ({ ...prev, confirmPassword: e.target.value }))}
                          className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500"
                        />
                      </div>
                      <button
                        onClick={handleChangePassword}
                        disabled={isSaving}
                        className="bg-primary-500 text-white px-4 py-2 rounded-lg font-medium hover:bg-primary-600 transition-colors disabled:opacity-50"
                      >
                        {isSaving ? 'Updating...' : 'Update Password'}
                      </button>
                    </div>
                  </div>

                  <div className="border-t border-gray-200 pt-6">
                    <h4 className="font-medium text-gray-900 mb-3">Two-Factor Authentication</h4>
                    <div className="bg-gray-50 rounded-lg p-4">
                      <div className="flex items-center justify-between">
                        <div>
                          <h5 className="font-medium text-gray-900">Authenticator App</h5>
                          <p className="text-sm text-gray-600">Use an authenticator app to generate verification codes</p>
                        </div>
                        <button className="bg-gray-400 text-white px-4 py-2 rounded-lg font-medium cursor-not-allowed">
                          Coming Soon
                        </button>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-gray-200 pt-6">
                    <h4 className="font-medium text-gray-900 mb-3">Danger Zone</h4>
                    <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                      <div className="flex items-center justify-between">
                        <div>
                          <h5 className="font-medium text-red-900">Delete Account</h5>
                          <p className="text-sm text-red-700">Permanently delete your account and all associated data</p>
                        </div>
                        <button
                          onClick={handleDeleteAccount}
                          disabled={isSaving}
                          className="bg-red-500 text-white px-4 py-2 rounded-lg font-medium hover:bg-red-600 transition-colors disabled:opacity-50"
                        >
                          Delete Account
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Settings;
